fix strict type CompanyTypeClient
fond-of/spryker-company-type pull request #7
Opened 2020-09-28 14:13 UTC by gengjozsef

2020-09-29 07:44 UTC, daniel-rose requested changes
remove deprecated stuff

2020-09-29 07:44 UTC, daniel-rose commented on src/FondOfSpryker/Client/CompanyType/Zed/CompanyTypeStub.php
> +     *
remove line (phpcs)

2020-09-29 07:44 UTC, daniel-rose commented on src/FondOfSpryker/Zed/CompanyType/Business/Model/CompanyTypeReaderInterface.php
> +     *
remove line (phpcs)

2020-09-29 10:16 UTC, gengjozsef commented on src/FondOfSpryker/Client/CompanyType/Zed/CompanyTypeStub.php
> +     *
done

2020-09-29 10:16 UTC, gengjozsef commented on src/FondOfSpryker/Zed/CompanyType/Business/Model/CompanyTypeReaderInterface.php
> +     *
done

2020-10-01 07:28 UTC, daniel-rose approved these changes

2020-10-01 07:28 UTC, merged